from typing import Literal

BankCode = Literal[
    "bg",
    "bnb",
    "bmsc",
    "bisa",
    "baneco",
    "bancosol",
    "bancounion",
]

BoliviaDepartment = Literal[
    "BENI",
    "PANDO",
    "ORURO",
    "LA_PAZ",
    "TARIJA",
    "POTOSI",
    "SANTA_CRUZ",
    "CHUQUISACA",
    "COCHABAMBA",
]

bank_columns: dict[BankCode, dict[str, str]] = {
    "bg": {
        "id": "bankid",
        "tipo": "type",
        "nombre": "name",
        "subtipo": "subtype",
        "latitud": "latitude",
        "direccion": "address",
        "longitud": "longitude",
        "telefono": "phonenumber",
        "descripcion": "description",
    },
    "bnb": {
        "id": "bankid",
        "tipo": "type",
        "subtipo": "subtype",
        "latitud": "latitude",
        "direccion": "address",
        "longitud": "longitude",
        "telefonos": "phonenumber",
        "horarios": "opening_hours",
        "descripcion": "description",
        "departamento": "department",
    },
    "bisa": {
        "id": "bankid",
        "notes": "additional_info",
        "telephone": "phonenumber",
        "working_hours": "opening_hours",
    },
    "bmsc": {
        "id": "bankid",
        "tipo": "type",
        "nombre": "name",
        "ciudad": "city",
        "latitud": "latitude",
        "direccion": "address",
        "longitud": "longitude",
        "telefono": "phonenumber",
        "departamento": "department",
        "horario_atencioncms": "opening_hours",
        "servicios_ofertados": "additional_info",
    },
    "baneco": {
        "id": "bankid",
        "tipo": "type",
        "nombre": "name",
        "latitud": "latitude",
        "direccion": "address",
        "longitud": "longitude",
        "telefonos": "phonenumber",
        "horarios": "opening_hours",
        "departamento": "department",
    },
    "bancosol": {
        "id": "bankid",
        "phone": "phonenumber",
        "working_hours": "opening_hours",
    },
    "bancounion": {
        "id": "bankid",
        "tipo": "type",
        "subtipo": "subtype",
        "latitud": "latitude",
        "longitud": "longitude",
        "direccion": "address",
        "telefono": "phonenumber",
        "descripcion": "description",
        "horario_atencion": "opening_hours",
    },
}
